credentials:
  usernames:
    rjoeneil:
      email: joeX@X.com
      name: Joe X
      password: $2b$12$D3bhzEufor4GjXvDa8m8EeJHpH1xLsr.zR7KcJ6EtPRYyaNhquAw6
      
cookie:
  expiry_days: 0
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - joeX@X.com