credentials:
  usernames:
    rjoeneil:
      email: joeneil.taguan@rci.rogers.com
      name: Joe Neil
      password: $2b$12$D3bhzEufor4GjXvDa8m8EeJHpH1xLsr.zR7KcJ6EtPRYyaNhquAw6
    rcarmela:
      email: carmela.cuaresma@rci.rogers.com
      name: Carmela Cuaresma
      password: $2b$12$D3bhzEufor4GjXvDa8m8EeJHpH1xLsr.zR7KcJ6EtPRYyaNhquAw6     
    raya:
      email: aya.atchkova@rci.rogers.com
      name: Aya Atchkova
      password: $2b$12$D3bhzEufor4GjXvDa8m8EeJHpH1xLsr.zR7KcJ6EtPRYyaNhquAw6  
    randrew:
      email: andrew.wong@rci.rogers.com
      name: Andrew Wong
      password: $2b$12$D3bhzEufor4GjXvDa8m8EeJHpH1xLsr.zR7KcJ6EtPRYyaNhquAw6  
    raaron:
      email: aaron.shi@rci.rogers.com
      name: Aaron Shi
      password: $2b$12$D3bhzEufor4GjXvDa8m8EeJHpH1xLsr.zR7KcJ6EtPRYyaNhquAw6        
    rnick:
      email: Nicholas.HoKoon@rci.rogers.com
      name: Nicholas HoKoon
      password: $2b$12$D3bhzEufor4GjXvDa8m8EeJHpH1xLsr.zR7KcJ6EtPRYyaNhquAw6        
    rmahmoud:
      email: Mahmoud.ElMeligui@rci.rogers.com
      name: Mahmoud ElMeligui
      password: $2b$12$D3bhzEufor4GjXvDa8m8EeJHpH1xLsr.zR7KcJ6EtPRYyaNhquAw6        
    rdinesh:
      email: Dinesh.Lukose@rci.rogers.com
      name: Dinesh Lukose
      password: $2b$12$D3bhzEufor4GjXvDa8m8EeJHpH1xLsr.zR7KcJ6EtPRYyaNhquAw6              
      
cookie:
  expiry_days: 0
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - joeneil.taguan@rci.rogers.com