credentials:
  usernames:
    yellowcar:  # The username for the yellowcar account  #bas64 encoding 
      email: yellowcar@arrow.com
      name: Yello OwCar
      password: xxxxxx #bas64 encoding 
            
cookie:
  expiry_days: 0
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - yellowcar@